apiVersion: v1
data:
  conf.json: |+
    {
        "app" : {
            "name": "nemesis.soul"
        },
        "transporter": {
            "amqp": {
                "address": "amqp://dedo-rabbit"
            },
        "exchange": "nemesis.soul",
            "producer": {
                "exchange": "",
                "routingKey": "nemesis.cannon"
            },
            "bulletConsumer": {
                "exchange": "nemesis.soul",
                "name": "nemesis.magazine",
                "tag": "req",
                "routingKey": "bullet",
                "autoAck": false
            },
            "smokeConsumer": {
                "exchange": "nemesis.soul",
                "name": "nemesis.magazine",
                "tag": "res",
                "routingKey": "smoke",
                "autoAck": false
            }
        }
    }
kind: ConfigMap
metadata:
  name: soul-config
 