apiVersion: v1
data:
  conf.json: |+
    {
        "port": 9000,
        "app" : {
            "name": "nemesis.adapter"
        },
        "gateway": {
            "base": "/nemesis/connect"
        },
        "transporter": {
            "amqp": {
                "address": "amqp://dedo-rabbit"
            },
            "producer": {
                "exchange": "nemesis.soul",
                "routingKey": "bullet"
            },
            "rpcConsumer": {
                "tag": "",
                "autoAck": false
            }
        }
    }
kind: ConfigMap
metadata:
  name: adapter-config
