apiVersion: apps/v1
kind: Deployment
metadata:
  name: cannon-deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  selector:
    matchLabels:
      app: nemesis.cannon
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nemesis.cannon
    spec:
      containers:
      - image: dedorewan/nemesis.cannon
        imagePullPolicy: Always
        name: adapter-container
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
        volumeMounts:
        - mountPath: /build/config
          name: config-vol
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          name: cannon-config
        name: config-vol