kind: Service
apiVersion: v1
metadata:
  name: dedo-rabbit
spec:
  selector:
    app: dedo-rabbit
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: wow
    port: 15672
    targetPort: 15672